apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: "postgres"
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: database_name
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: database_port
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: database_password
            - name: BE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: jwt_secret
            - name: BE_JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: jwt_refresh_secret

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8111
      targetPort: 80
  type: LoadBalancer
